language: python

env:
  global:
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - python: "2.6"
      env: TESTENVS="cp26"
    - python: "2.7"
      env: TESTENVS="cp27"
    - python: "3.3"
      env: TESTENVS="cp33"
    - python: "3.4"
      env: TESTENVS="cp34"
    - python: "3.5"
      env: TESTENVS="cp35"
    - python: "3.6"
      env: TESTENVS="cp36"
    - dist: xenial
      python: "3.7"
      env: TESTENVS="cp37"
    - python: "pypy"
      env: TESTENVS="pypy"
    - python: "pypy3"
      env: TESTENVS="pypy3"
    - os: osx
      language: shell
      env: TOXPY37="/usr/local/bin/python2" TESTENVS="cp27"
      python: "2.7"
    - os: osx
      language: shell
      env: TOXPY36="/usr/local/bin/python3" TESTENVS="cp36"
      python: "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

branches:
  only:
    - master
    - /^maintenance\/.*$/
    - /^v\d+\.\d+\.\d+.*$/

addons:
  homebrew:
    packages:
    - python@2
    - python@3

before_cache:
    - brew cleanup

install:
  - pip install tox

script:
  - tox -e ${TESTENVS}

notifications:
  email:
    - travis-ci@simonjagoe.com

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install "idna < 2.8"; fi
  - pip install coveralls
  - coveralls
