language: python

env:
  global:
      PYTHONUNBUFFERED="1"

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - dist: xenial
      python: 3.7
    - python: pypy
    - python: pypy3
    - os: osx
      language: shell
      python: 2.7
    - os: osx
      language: shell
      python: 3.7


cache:
  directories:
    - $HOME/.cache/pip

branches:
  only:
    - master
    - /^maintenance\/.*$/
    - /^v\d+\.\d+\.\d+.*$/

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ; fi
  - |
    if [[ ${TRAVIS_OS_NAME} == 'osx' ]]; then
       brew update
       brew install python
    fi
  - python setup.py develop
  - pip install coverage
  - pip install -r test_requirements.txt
  - pip --version
  - python -V

script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
       coverage run --branch -m unittest2.__main__ discover -v -t . haas
       python -m haas.__main__
    else
       coverage run --branch -m unittest discover -v -t . haas
       python -m haas
    fi

notifications:
  email:
    - travis-ci@simonjagoe.com

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install "idna < 2.8"; fi
  - pip install coveralls
  - coveralls
