language: python
python:
  - 2.7
  - 2.6
install:
  - if ! [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; then pip install unittest2 ; fi
  - pip install coverage
  - pip install coveralls
  - python setup.py develop
script:
  - if ! [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; coverage run --branch -m unittest2 discover -v -t . haas
  - if [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; coverage run --branch -m unittest discover -v -t . haas
notifications:
  email:
    - travis-ci@simonjagoe.com
after_success:
  coveralls
