language: python

env:
  global:
      PYTHONUNBUFFERED="1"
      TOX_REQUIREMENT="tox"
matrix:
  include:
    - python: "2.6"
      env: TOXENV="cp26"
    - python: "2.7"
      env: TOXENV="cp27"
    - python: "3.3"
      env: TOXENV="cp33"
    - python: "3.4"
      env: TOXENV="cp34"
    - python: "3.5"
      env: TOXENV="cp35"
    - python: "3.6"
      env: TOXENV="cp36"
    - dist: xenial
      python: "3.7"
      env: TOXENV="cp37"
    - python: "pypy"
      env: TOXENV="pp2"
    - python: "pypy3"
      env: TOXENV="pp3"
    - os: osx
      language: shell
      env: TOXPY27="/usr/local/bin/python2" TOXENV="cp27"
      python: "2.7"
    - os: osx
      language: shell
      env: TOXPY36="/usr/local/bin/python3" TOXENV="cp36"
      python: "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

branches:
  only:
    - master
    - /^maintenance\/.*$/
    - /^v\d+\.\d+\.\d+.*$/

addons:
  homebrew:
    packages:
    - python@2
    - python@3

before_cache:
    - brew cleanup

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python -m pip install -U pip; fi
  - pip install -rtox-requirements.txt

script:
  - tox -v

notifications:
  email:
    - travis-ci@simonjagoe.com

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install "idna < 2.8"; fi
  - pip install coveralls
  - coveralls
