language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5
    - python: pypy
    - python: pypy3

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ; fi
  - python setup.py develop
  - pip install coverage
  - pip install -r test_requirements.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
       coverage run --branch -m unittest2.__main__ discover -v -t . haas;
       python -m haas.__main__;
    else
       coverage run --branch -m unittest discover -v -t . haas; fi
       python -m haas;
    fi

notifications:
  email:
    - travis-ci@simonjagoe.com

after_success:
  - pip install coveralls
  - coveralls
