language: python

env:
  global:
      PYTHONUNBUFFERED="1"

matrix:
  include:
    # - python: 2.6
    # - python: 2.7
    # - python: 3.3
    # - python: 3.4
    # - python: 3.5
    # - python: 3.6
    # - dist: xenial
    #   python: 3.7
    # - python: pypy
    # - python: pypy3
    - os: osx
      language: shell
      env: TOXPY37="/usr/local/bin/python2" TESTENVS="cp27"
      python: 2.7
    - os: osx
      language: shell
      env: TOXPY37="/usr/local/bin/python3" TESTENVS="cp37"
      python: 3.7

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew

branches:
  only:
    - master
    - /^maintenance\/.*$/
    - /^v\d+\.\d+\.\d+.*$/

addons:
  homebrew:
    packages:
    - python@2
    - python@3

before_cache:
    - brew cleanup

install:
  - pip install tox

script:
  - tox -e ${TESTENVS}

notifications:
  email:
    - travis-ci@simonjagoe.com

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install "idna < 2.8"; fi
  - pip install coveralls
  - coveralls
