build: false
shallow_clone: true
skip_branch_with_pr: true
image: Visual Studio 2015

environment:

  pythonunbuffered: "1"
  toxenv: "cp26-win,cp27,cp33,cp34,cp35,cp36,cp37"

  matrix:
    - TOXPY26: "C:/Python26-x64/python.exe"
      TOXPY27: "C:/Python27-x64/python.exe"
      TOXPY33: "C:/Python33-x64/python.exe"
      TOXPY34: "C:/Python34-x64/python.exe"
      TOXPY35: "C:/Python35-x64/python.exe"
      TOXPY36: "C:/Python36-x64/python.exe"
      TOXPY37: "C:/Python37-x64/python.exe"
      PYTHON: "C:/Python27-x64"
    - TOXPY26: "C:/Python26/python.exe"
      TOXPY27: "C:/Python27/python.exe"
      TOXPY33: "C:/Python33/python.exe"
      TOXPY34: "C:/Python34/python.exe"
      TOXPY35: "C:/Python35/python.exe"
      TOXPY36: "C:/Python36/python.exe"
      TOXPY37: "C:/Python37/python.exe"
      PYTHON: "C:/Python33"

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache -> appveyor-cache.txt

init:
  - ps: $Env:path = $Env:PYTHON + ";" + $Env:PYTHON + "/Scripts;" + $Env:path
install:
  - cmd: python -m pip install -rtox-requirements.txt
test_script:
  - python -m tox -v
on_success:
  - python -m pip install codecov
  - python -m codecov
