name: Test

on:
  pull_request:
  push:
    branches:
      - master
      - maintenance/**
    tags:
      - "v*"

env:
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "pypy2", "pypy3"]
        os: [windows-2019, ubuntu-22.04, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}  
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        pip install -e .
        pip install -r "test_requirements.txt"
        pip --version
    - name: Run tests with unittest
      run: |
        coverage run --branch -m unittest discover -v -t . haas
    - name: Run tests with haas
      run: |
        python -m haas haas
    - name: Print coverage report
      run: |
        coverage report

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install flake8
      run: python -m pip install flake8
    - name: Lint codebase
      run: python -m flake8 haas
