name: Test

on:
  pull_request:
    branches:
      - master
      - maintenance/**
  push:
    branches:
      - master
      - maintenance/**
    tags:
      - "v*"

env:
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    needs: [lint]
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11", '3.12', 'pypy2', 'pypy3']
        os: [windows-2019, ubuntu-20.4, macos-11]
      fail-fast: false
    runs-on: ${{ matrix.os }}  
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-verison }}
    - name: Install
      run: |
        pip install -e .
        pip install -r "test_requirements.txt"
        pip --version
    - name: Run tests
      continue-on-error: false
      working-directory: .github
      run: |
        python -m unittest discover haas
        python -m haas haas
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install flake8
      run: python -m pip install flake8
    - name: Lint codebase
      run: python -m flake8 haas
