name: Test

on:
  pull_request:
    branches: [master]
  push: {}

env:
  PYTHONUNBUFFERED: "1"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-18.04
            python: "2.7"
            toxenv: cp27
          - os: ubuntu-18.04
            python: "3.3"
            toxenv: cp33
          - os: ubuntu-18.04
            python: "3.4"
            toxenv: cp34
          - os: ubuntu-18.04
            python: "3.5"
            toxenv: cp35

          - os: ubuntu-18.04
            python: "pypy2"
            toxenv: pp2
          - os: ubuntu-18.04
            python: "pypy3"
            toxenv: pp3

          - os: ubuntu-20.04
            python: "2.7"
            toxenv: cp27
          - os: ubuntu-20.04
            python: "3.5"
            toxenv: cp35
          - os: ubuntu-20.04
            python: "pypy2"
            toxenv: pp2
          - os: ubuntu-20.04
            python: "pypy3"
            toxenv: pp3

          - os: macos-10.15
            python: "3.5"
            toxenv: cp35
          - os: macos-11.0
            python: "3.5"
            toxenv: cp35
          - os: windows-2019
            python: "3.5"
            toxenv: cp35

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: pip install -q -r "tox-requirements.txt"
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox -v
